### ISSUE TITLE
Add example analysis to README or Vignette

### ISSUE THREAD

**Issue by TommyJones** [JonasRieger/ldaPrototype#1]
Relating to JOSS review [here](https://github.com/openjournals/joss-reviews/issues/2181#issuecomment-623142268)

There is no example usage of how to use the software for an analysis problem. A great place to put this would be in the README, showing basic usage. If you want to cover more ground than one would typically put in a README, a vignette is a good place. But without this, I'm not sure where to start and thus can't check functionality.

**Comment by JonasRieger** [comment]
Thanks for the comment. I fixed it. https://github.com/JonasRieger/ldaPrototype/commit/7b17307cb5b760650d23e03aa8cba6590c0e996d
