### ISSUE TITLE
Contribution guidelines (as opposed to code of conduct) are unclear

### ISSUE THREAD

**Issue by TommyJones** [JonasRieger/ldaPrototype#2]
Related to JOSS review [here](https://github.com/openjournals/joss-reviews/issues/2181#issuecomment-623142268)

The community guidelines do not have a clear statement or instructions for contributing. Adding a sentence to the bottom of the README would fix that right up.

**Comment by JonasRieger** [comment]
https://github.com/JonasRieger/ldaPrototype/commit/6646d425d72a6c78360aac3e2b685829e7b8e9b5
