### ISSUE TITLE
Defaults and Documentation

### ISSUE THREAD

**Issue by bstewart** [JonasRieger/ldaPrototype#6]
Regarding the JOSS review, I'd recommend documenting the default parameters passed to `lda.collapsed.gibbs.sampler` in the help files for the functions that call it. This is particularly important for those which don't have defaults or have different defaults in the original package.

It is a stylistic choice but I'd also give some consideration to removing the default for `K`.  Users rarely change defaults and I think a reason that other packages don't offer a default for `K` is a way of signaling that it is something that the user really has to engage with.

**Comment by JonasRieger** [comment]
Fixed it, thank you for your comments. I am with you that `K` should not have a default!
edit: https://github.com/openjournals/joss-reviews/issues/2181
